name: chakravyuh
description: "A new Flutter project."

publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ^3.5.1

dependencies:
  google_sign_in: ^5.4.3

  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  flutter_svg: ^2.0.14

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/Theme-img.png
    - assets/images/Logo-Frame.png
    - assets/images/log.jpg
    - assets/images/google.png
    - assets/images/image.png

  fonts:
    - family: ShantellSans
      fonts:
        - asset: fonts/ShantellSans-Regular.ttf
        - asset: fonts/ShantellSans-Bold.ttf
          weight: 700
