name: chakravyuh
description: "A new Flutter project."

publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ^3.5.1

dependencies:
  google_sign_in: ^5.4.3

  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  flutter_svg: ^2.0.14

  http: ^1.2.2

  curved_navigation_bar: ^1.0.6
  convex_bottom_bar: ^3.2.0
  firebase_auth: ^5.3.3
  firebase_core: ^3.8.0
  cloud_firestore: ^5.5.0
  shared_preferences: ^2.3.3
  provider: ^6.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/Theme-img.png
    - assets/images/Logo-Frame.png
    - assets/images/date.png
    - assets/images/google.png
<<<<<<< HEAD
    - assets/images/image.png
    - assets/images/guide.jpg
    - assets/aries.png
    - assets/taurus.png
    - assets/gemini.png
    - assets/cancer.png
    - assets/leo.png
    - assets/virgo.png
    - assets/libra.png
    - assets/scorpio.png
    - assets/sagittarius.png
    - assets/capricorn.png
    - assets/aquarius.png
    - assets/pisces.png
=======
    - assets/images/time.png
    - assets/images/profile.png
    - assets/images/capricon.png
    - assets/images/location.png
    - assets/icons/arrow.svg
    - assets/icons/dott.svg
    - assets/images/aeris.jpg
    - assets/images/taurus.jpg
    - assets/images/gemini.jpg
    - assets/images/cancer.jpg
    - assets/images/leo.jpg
    - assets/images/virgo.jpg
    - assets/images/libra.jpg
    - assets/images/scorpio.jpg
    - assets/images/sagittarius.jpg
    - assets/images/capricon.jpg
    - assets/images/Aquarius.jpg
    - assets/images/Pisces.jpg
>>>>>>> 677dd7f79979e1ce9ae0f9fcacfbf7af102fc0da

  fonts:
    - family: ShantellSans
      fonts:
        - asset: fonts/ShantellSans-Regular.ttf
        - asset: fonts/ShantellSans-Bold.ttf
          weight: 700
