// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA5cmZ1yEK6pY90ArjCjRHpwlUUNYxqdQU',
    appId: '1:338945194705:web:4a5fafcd38f68152bae3f0',
    messagingSenderId: '338945194705',
    projectId: 'chakravyuh-astrology-app',
    authDomain: 'chakravyuh-astrology-app.firebaseapp.com',
    storageBucket: 'chakravyuh-astrology-app.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDa0QfdZx3S3VoGpq_plHIMLp4fwwUD_30',
    appId: '1:338945194705:android:972f972045a24488bae3f0',
    messagingSenderId: '338945194705',
    projectId: 'chakravyuh-astrology-app',
    storageBucket: 'chakravyuh-astrology-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA2VgnYe5guTn6_rpVSvmOpp8nvl0nW-HE',
    appId: '1:338945194705:ios:277b77c8f9e1559bbae3f0',
    messagingSenderId: '338945194705',
    projectId: 'chakravyuh-astrology-app',
    storageBucket: 'chakravyuh-astrology-app.firebasestorage.app',
    iosBundleId: 'com.example.chakravyuh',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA2VgnYe5guTn6_rpVSvmOpp8nvl0nW-HE',
    appId: '1:338945194705:ios:277b77c8f9e1559bbae3f0',
    messagingSenderId: '338945194705',
    projectId: 'chakravyuh-astrology-app',
    storageBucket: 'chakravyuh-astrology-app.firebasestorage.app',
    iosBundleId: 'com.example.chakravyuh',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA5cmZ1yEK6pY90ArjCjRHpwlUUNYxqdQU',
    appId: '1:338945194705:web:8024ee00991f29e2bae3f0',
    messagingSenderId: '338945194705',
    projectId: 'chakravyuh-astrology-app',
    authDomain: 'chakravyuh-astrology-app.firebaseapp.com',
    storageBucket: 'chakravyuh-astrology-app.firebasestorage.app',
  );
}
